augmented-pandemic/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import views as auth_views

urlpatterns = [
	url(r'^game/', include('game.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/game'
    )),
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', auth_views.logout, {'next_page': '/game/logout_successful/'}),
    url(r'^', include('django.contrib.auth.urls')),    
]

game/urls.py
"""Mapping game URLs to views"""

from django.conf.urls import url
from django.contrib import admin

from . import views

app_name = 'game'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^users/$', views.users, name='users'),
    url(r'^user_search/$', views.user_search, name='user_search'),
    url(r'^user_detail/', views.user_detail, name='user_detail'),
    url(r'^leaderboard/$', views.leaderboard, name='leaderboard'),
    url(r'^play/$', views.play, name='play'),
    url(r'^database/location_json/$', views.location_json, name='location_json'),
    url(r'^database/safezone_json/$', views.safezone_json, name='safezone_json'),
    url(r'^database/announcement_json/$', views.announcement_json, name='announcement_json'),
    url(r'^database/current_profile_json/$', views.current_profile_json, name='current_profile_json'),
    url(r'^logout_successful/$', views.logout_successful, name='logout_successful'),
    url(r'^admin/', admin.site.urls),
    url(r'^(?P<location_name>.+)/win/$', views.win, name='win'),
    url(r'^(?P<location_name>.+)/lose/$', views.lose, name='lose'),
    url(r'^(?P<location_name>.+)/antidoteReceived/$', views.antidoteReceived, name='antidoteReceived'),
    url(r'^(?P<location_name>.+)/antidoteUsed/$', views.antidoteUsed, name='antidoteUsed'),
]

game/models.py
"""Game app models"""

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Location(models.Model):
    """Regions of infection"""
    location_text = models.CharField(max_length=200)
    zone_text = models.CharField(max_length=200, default="")
    matches_lost = models.IntegerField(default=30)
    matches_won = models.IntegerField(default=70)

    def total_matches(self):
        """Returns total matches played in region"""
        won = self.matches_won
        lost = self.matches_lost
        return float(won + lost)

    def infection_rate(self):
        """Returns infection rate of location"""
        rate = (self.matches_lost / self.total_matches())*100
        return rate

    def __str__(self):
        """Returns location name"""
        return self.location_text

class Safezone(models.Model):
    """Regions of infection"""
    location_text = models.CharField(max_length=200)
    zone_text = models.CharField(max_length=200, default="")
    antidotes_in_stock = models.IntegerField(default=25)
    antidotes_given_out = models.IntegerField(default=0)

    def __str__(self):
        """Returns location name"""
        return self.location_text

class Announcement(models.Model):
    """Stores announcements/update to game"""
    announcement_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.announcement_text

class Profile(models.Model):
    """User Profile model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    matches_won = models.IntegerField(default=0)
    matches_lost = models.IntegerField(default=0)
    num_antidotes = models.IntegerField(default=0)

    def total_matches(self):
        """Returns total matches played"""
        won = self.matches_won
        lost = self.matches_lost
        return float(won + lost)

    def success_rate(self):
        """Returns matches won out of total matches"""
        if self.total_matches() == 0:
            success = 0
            return success
        else:
            success = (self.matches_won / self.total_matches())*100
            success = round(success, 2)
            return success

    def __str__(self):
        return self.user

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        """A user profile is created when user is created"""
        if created:
            Profile.objects.create(user=instance)

    #@receiver(post_save, sender=User)
    #def save_user_profile(sender, instance, **kwargs):
    #    instance.profile.save()

game/views.py
"""Game views"""
import json
import logging
logger = logging.getLogger(__name__)
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
#from django.urls import reverse
from django.core import serializers
#from django.contrib.auth import logout
#from django.views import View

from .models import Location, User
from .models import Safezone
from .models import Announcement
from .models import Profile

def index(request):
    """Homepage view"""
    context = {'text': 'Welcome to our game. Click "Fight the Infection" above to play!'}
    return render(request, 'game/index.html', context)

def logout_successful(request):
    """Displays logout success message when user log out"""
    context = {'text': 'Logout successful'}
    return render(request, 'game/logout_successful.html', context)

def users(request):
    """User search home"""
    context = {'text': 'Find a user:'}
    return render(request, 'game/users.html', context)

def user_search(request):
    """Receive search input and search database for user"""
    query = request.GET.get('user_id') # receive user input
    if query:
        users_found = User.objects.filter(username__contains=query) # find users based on input
        if not users_found: # if no users found based on user input
            none = 'No users found.'
            context = {'searched': query, 'none': none}
        else:
            rates = []
            for i in users_found: # if users found based on user input
                rates.append(i.profile.success_rate()) # get user success rates from user's profile
                results = zip(users_found, rates) # zip lists for easy iteration
            context = {'searched': query, 'results': results}
    else:
        context = {'searched': 'No input detected.'} # if no input sent

    return render(request, 'game/search_results.html', context)

def user_detail(request):
    """User profile view"""
    if request.user.is_authenticated: # get user profile info if logged in
        current_user = request.user
        context = {'username': current_user.username,
                   'total_matches': int(current_user.profile.total_matches()),
                   'matches_won': int(current_user.profile.matches_won),
                   'win_rate': current_user.profile.success_rate(),
                   'num_antidotes': current_user.profile.num_antidotes
                  }
        return render(request, 'game/user_detail.html', context)
    else:
        return HttpResponseRedirect('/login')

def leaderboard(request):
    """Leaderboard view *Noted naive sorting logic to not risk breaking app"""
    get_users = Profile.objects.order_by('-matches_won')[:5]
    #get_users = Profile.objects.order_by('-success_rate')[:5]
    text = ""
    if not get_users:
        text = "No users in database yet."
    rates = []
    user_list = []
    matches = []
    for i in get_users: # get 3 lists with username, succes rate, and total matches played
        current_user = i.user
        user_list.append(current_user.username)
        rates.append(i.success_rate())
        matches.append(int(i.total_matches()))
    ranking = list(zip(user_list, rates, matches)) # zip for easy iteration
    context = {'text': text, 'ranking': ranking, 'get_users': get_users, 'matches': matches,
               'rates': rates}

    return render(request, 'game/leaderboard.html', context)

def play(request):
    """Game view"""
    current_user = request.user
    if current_user.is_anonymous(): # user must be logged in to get data
        num_antidotes = "Please log in to use antidotes!"
    else:
        num_antidotes = current_user.profile.num_antidotes
    context = {'antidotes': num_antidotes}

    return render(request, 'game/play.html', context)

def location_json(request):
    """Retrieving location information from db"""
    if request.method == "GET":
        location_list = Location.objects.all()
        location_json_list = serializers.serialize('json', location_list)
        location_object = json.loads(location_json_list) # Convert JSON to python dict

        # Create a new object and make the keys be the location names so it's easier to search later
        output_object = {}
        for location in location_object:
            location_text = location['fields']['location_text']
            output_object[location_text] = location

        return HttpResponse(json.dumps(output_object), content_type='application/javascript')

def safezone_json(request):
    """Retrieving safezone locations from db"""
    if request.method == "GET":
        safezone_list = Safezone.objects.all()
        safezone_json_list = serializers.serialize('json', safezone_list)
        safezone_object = json.loads(safezone_json_list) # Convert JSON to python dict

        # Create a new object and make the keys be the location names so it's easier to search later
        output_object = {}
        for location in safezone_object:
            location_text = location['fields']['location_text']
            output_object[location_text] = location

        return HttpResponse(json.dumps(output_object), content_type='application/javascript')
# Fix this
def current_profile_json(request):
    """Retrieving user profile data from db"""
    if request.method == "GET":
        if request.user.is_authenticated:
            current_user = request.user
            output_object = {}
            output_object['num_antidotes'] = current_user.profile.num_antidotes
            return HttpResponse(json.dumps(output_object), content_type='application/javascript')
        else:
            return HttpResponse("No logged in user")

def win(request, location_name):
    """Saving matches won to db"""
    if request.method == "POST":
        location = get_object_or_404(Location, location_text=location_name) #get current location
        location.matches_won += 1
        location.save()

        # save win information to current user's profile
        if request.user.is_authenticated:
            current_user = request.user
            current_user.profile.matches_won += 1
            current_user.profile.save()

    return HttpResponse("matches_won increased by 1")

def lose(request, location_name):
    """Saving matches lost to db"""
    if request.method == "POST":
        location = get_object_or_404(Location, location_text=location_name)
        location.matches_lost += 1
        location.save()

        # save lose information to current user's profile
        if request.user.is_authenticated:
            current_user = request.user
            current_user.profile.matches_lost += 1
            current_user.profile.save()

    return HttpResponse("matches_lost increased by 1")

def antidoteReceived(request, location_name):
    """Saving antidotes changes to db"""
    if request.method == "POST":
        safezone = get_object_or_404(Safezone, location_text=location_name)
        safezone.antidotes_in_stock -= 1
        safezone.antidotes_given_out += 1
        safezone.save()

        # save increased antidote number information to current user's profile
        if request.user.is_authenticated:
            current_user = request.user
            current_user.profile.num_antidotes += 1
            current_user.profile.save()

    return HttpResponse("received antidote")

def antidoteUsed(request, location_name):
    """Saving antidotes changes to db"""
    if request.method == "POST":
        location = get_object_or_404(Location, location_text=location_name)
        location.matches_won += 5
        location.save()

        # save increased antidote number information to current user's profile
        if request.user.is_authenticated:
            current_user = request.user
            current_user.profile.num_antidotes -= 1
            current_user.profile.save()

    return HttpResponse("used antidote")

def announcement_json(request):
    """Retrieving announcements from db"""
    if request.method == "GET":
        announcement_list = Announcement.objects.all()
        announcement_json_list = serializers.serialize('json', announcement_list)
        announcement_object = json.loads(announcement_json_list) # Convert JSON to python dict

        # Create a new object and make the keys be the location names so it's easier to search later
        output_object = {}
        for announcement in announcement_object:
            announcement_text = announcement['fields']['announcement_text']
            output_object[announcement_text] = announcement

        return HttpResponse(json.dumps(output_object), content_type='application/javascript')

game/templates/game/index.html
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<title>Augmented Pandemic Home Page</title>
		{% load static %}
		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'game/css/index.css' %}" />
		<link href="https://fonts.googleapis.com/css?family=Monda" rel="stylesheet">
	</head>
	<body>
		<div id="navbar">{% include "game/navigation_bar.html" %}</div>
		<div class="mainContent">
			<p>{{ text }}</p>
			<h1>Announcements</h1>
			<div id="announcementWindow"></div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="{% static 'game/js/index.js' %}"></script>
	</body>
</html>

game/templates/game/leaderboard.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
      <meta charset="utf-8">
        <title>Leaderboard</title>
        {% load static %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Monda" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/leaderboard.css' %}" />
    </head>
    <body>
        {% include "game/navigation_bar.html" %}
        <h1>Leaderboard</h1>
        <table class="center">
            {{ text }}
            {% if ranking %}
            <tr>
                <th>USERNAME</th>
                <th>Cure Rate</th>
                <th>Total Matches Played</th>
            </tr>
            {% for list in ranking %}
            <tr>
                {% for i in list %}
                <td>{{ i }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
            {% endif %}
        </table>
        <br>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

game/templates/game/leaderboardry.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>


h1 {text-align:center;
}
table {
    width:100%;
}
table, th, td {
    border: 1px solid red;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}

</style>
</head>
<body>
<h1> Augmented Leaders </h1>
<table>
  <tr>
    <th>USERNAME</th>
    <th>CURE RATE</th>
  </tr>
  <tr>
    <td>Jordon</td>
    <td>1000</td>
  </tr>
  <tr>
    <td>Smith</td>
    <td>750</td>
  </tr>
  <tr>
    <td>Josh</td>
    <td>500</td>
  </tr>
</table>
<br>

</body>
</html>

game/templates/game/login_backup.html
<form action="action_page.php">
	<div class="container">
		<label><b>Username</b></label>
		<input type="text" placeholder="Enter Username" name="uname" required><br>
		<label><b>Password</b></label>
		<input type="password" placeholder="Enter Password" name="psw" required><br>
		<input type="checkbox" checked="checked"> Remember me<br>
		<button type="submit">Login</button>
		<button type="button" class="cancelbtn">Cancel</button><br>
		<span class="psw">Forgot <a href="#">password?</a></span>
		<span class="psw"><a href="{% url 'game:register' %}">New user?</a></span>
	</div>
</form>

game/templates/game/logout_successful.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>Logout successful</title>
        {% load static %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro|Cousine|Monda" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/leaderboard.css' %}" />
    </head>
    <body>
        {% include "game/navigation_bar.html" %}
        <div class="text">
            <p>{{ text }}</p>
        </div>
        <script>
            function redirect(){
               window.location.href = "/game/";
            }
            setTimeout(redirect, 2000);
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

game/templates/game/navigation_bar.html
<!-- Bootstrap Navbar -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle grouped for better mobile display -->
        <div class="navbar-header">
        	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'game:play' %}">Fight the Infection</a>
        </div>
        <!-- Group links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
    			<li><a href="{% url 'game:index' %}">Home</a></li>
    			<li><a href="{% url 'game:users' %}">Users</a></li>
    			<li><a href="{% url 'game:leaderboard' %}">Leaderboard</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href = "{% url 'game:user_detail' %}">Welcome {{ user.username }}</a></li>
                    <li><a href="/logout">Logout</a></li>
                {% else %}
        			<li><a href="/register">Register</a></li>
        			<li><a href="/login">Login</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

game/templates/game/play.html
<!DOCTYPE html>
<html>
	<head>
		<title>Fight the Infection!</title>
		<meta name="viewport" content="initial-scale=1.0">
		<meta charset="utf-8">

		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Monda" rel="stylesheet">
		{% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/play.css' %}" />
	</head>
	<body>
		<div id="navigationBar">{% include "game/navigation_bar.html" %}</div>
		<h1 id="gameTitle">Fight the Infection</h1>
		<div id="textArea">
			<div id="leftSide">
                <p class="titles">
                    Zone: <span class="info" id="zoneText"></span>
                </p>
				<p class="titles">
					Subzone: <span class="info" id="subzoneText"></span>
				</p>
				<p class="titles" id="GlobalInfectionRate">
					Zone Infection Rate: <span class="info" id="global"></span>
				</p>
				<p class="titles" id="LocalInfectionRate">
					Subzone Infection Rate: <span class="info" id="local"></span>
				</p>
				<p class="titles" id="numAntidotesText">Number of antidotes: {{ antidotes }}</p>
				<div class="buttons" id="userSelection">
					{% csrf_token %}
					<button id="rockButton" class="RPSButton">Quarantine</button>
					<button id="paperButton" class="RPSButton">Cure</button>
					<button id="scissorsButton" class="RPSButton">Rescue</button>
                    {% if user.is_authenticated %}
                    |
                    <button id="useAntidoteButton">Use Antidote</button>
                    <button id="getAntidoteButton">Get Antidote</button>
                    {% endif %}
				</div><br>
				<div class="buttons" id="generalButtons">
					<input id="checkLocationButton" type="button" value="Check Location">
					<input id="centerMapButton" type="button" value="Center Map">
					<input id="toggleMapButton" type="button" value="Toggle Map">
                    <input id="helpButton" type="button" value="Help">
                    <input id="clearInfoWindowButton" type="button" value="Clear Info Window">
				</div>
			</div>
            <div id="rightSide">
                <div id="infoWindow"><p>Information Window</p></div>
            </div>
		</div>
		<div id="map"></div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="{% static 'game/js/play.js' %}"></script>
		<script src="{% static 'game/js/rockpaperscissor.js' %}"></script>
        <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA7lpJkNjlPd3Cl6UJAr7nAyM1U0eMTH6I&callback=initMap"></script>
	</body>
</html>

game/templates/game/register.html
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<title>User Registration Page</title>
	</head>
	<body>
		{% include "game/navigation_bar.html" %}
		<p>{{ text }}</p>
    <form action="action_page.php">

      <div class="container">
        <label><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required><br>
        <label><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required><br>
        <label><b>Confirm Password</b></label>
        <input type="password" placeholder="Retype Password" name="psw" required>
        <br><br>
        <button type="submit">Submit</button>
      </div>
    </form>
	</body>
</html>

game/templates/game/register_backup.html
<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
		<title>User Registration Page</title>
	</head>
	<body>
		{% include "game/navigation_bar.html" %}
		<p>{{ text }}</p>
    <form action="action_page.php">

      <div class="container">
        <label><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required><br>
        <label><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required><br>
        <label><b>Confirm Password</b></label>
        <input type="password" placeholder="Retype Password" name="psw" required>
        <br><br>
        <button type="submit">Submit</button>
      </div>
    </form>
	</body>
</html>

game/templates/game/search_results.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>User List</title>
        {% load static %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Monda" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/users.css' %}" />
    </head>
    <body>
      {% include "game/navigation_bar.html" %}
      <div class="text">
        <h1>Users</h1>
        <div id="users_found">
          You searched for: {{ searched }}<br><br>
          {{ none }}
          {% for i,j in results %}
          <p>{{ i }} | Success rate: {{ j }}%</p>
          {% endfor %}
        </div>
      </div>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

game/templates/game/user_detail.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>User Profile</title>
        {% load static %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Monda" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/users.css' %}" />
    </head>
    <body>
      {% include "game/navigation_bar.html" %}
      <div class="text">
        <h1>Hello, {{ username }}</h1>
        <div id="profile">
          <p>Total Matches Played: {{ total_matches }}</p>
          <p>Total Matches Won: {{ matches_won }}</p>
          <p>Lifetime Success Rate: {{ win_rate }}%</p>
          <p>Number of Antidotes: {{ num_antidotes }}<p>
        </div>
      </div>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>

game/templates/game/users.html
<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>User List</title>
        {% load static %}
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Monda" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'game/css/users.css' %}" />
    </head>
    <body>
      {% include "game/navigation_bar.html" %}
      <div class="text">
        <h1>Users</h1>
        <form id="user_search" action="{% url 'game:user_search' %}" method="get">
          {{ text }} <input type="text" name="user_id">
          <button type="submit">Search</button>
        </form>
        <div id="users_found"></div>
      </div>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>
</html>